package seat

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"syscall"
	"time"
)

// The command catalog, written into a workspace at spawn (facet#118).
//
// A seat currently learns the tool surface by running --help repeatedly, or by
// being told it in a prompt that goes stale. Both cost turns; the second costs
// correctness. The catalog is generated by the same introspection that feeds
// argano's console, so it cannot drift from the tools' real surface -- which is
// the property that made it worth having at spawn rather than in a prompt.
//
// # It is never absent
//
// A generation failure writes a file that SAYS it failed, and spawn exits
// non-zero. An absent file that means "generation failed" is indistinguishable
// from "not supported yet" -- the same defect class as `.mode`, which is always
// present precisely so that absence is a defect and never a state.

// CatalogFile is the file name, relative to a workspace root, beside .seat,
// .scope and .seat-issue.
const CatalogFile = ".catalog.json"

// catalogTimeout bounds the generation. argano introspects several binaries;
// a spawn must not be able to hang on one of them, because a spawn that never
// returns is a workspace nobody can tell is finished.
const catalogTimeout = 60 * time.Second

// CatalogResult says what happened, so the caller can report it in one line
// rather than the caller re-deriving it from the file.
type CatalogResult struct {
	Path string
	// OK is false when the catalog could not be generated or is incomplete.
	// The file exists either way.
	OK bool
	// Detail is the failure, ready to print. Empty when OK.
	Detail string
}

// WriteCatalog generates the command catalog into a workspace.
//
// bin is the argano binary. An empty bin, a missing binary, a non-zero exit or
// a timeout all produce a file explaining the failure rather than no file.
func WriteCatalog(workspaceDir, bin string) (CatalogResult, error) {
	return writeCatalogWithin(workspaceDir, bin, catalogTimeout)
}

// writeCatalogWithin is WriteCatalog with the deadline handed in, so a test can
// prove the deadline FIRES in milliseconds rather than in a minute.
func writeCatalogWithin(workspaceDir, bin string, timeout time.Duration) (CatalogResult, error) {
	path := filepath.Join(workspaceDir, CatalogFile)
	res := CatalogResult{Path: path}

	out, err := generateCatalog(bin, timeout)
	if err != nil {
		res.Detail = err.Error()
		// The failure goes in the FILE, in a shape a reader meets before any
		// parse: a consumer that only json-decodes gets a valid object saying
		// error, and a human opening it gets a sentence.
		body := fmt.Sprintf("{\n  \"error\": %q,\n  \"generated_by\": %q,\n  \"note\": %q\n}\n",
			err.Error(), bin,
			"the command catalog could not be generated; this file exists so that its ABSENCE is never mistaken for 'not supported yet'")
		if werr := writeAndVerify(path, []byte(body)); werr != nil {
			return res, werr
		}
		return res, nil
	}

	if werr := writeAndVerify(path, out); werr != nil {
		return res, werr
	}
	res.OK = true
	return res, nil
}

func generateCatalog(bin string, timeout time.Duration) ([]byte, error) {
	if bin == "" {
		return nil, fmt.Errorf("no argano binary to generate it with")
	}
	if _, err := os.Stat(bin); err != nil {
		return nil, fmt.Errorf("%s is not installed: %w", bin, err)
	}

	cmd := exec.Command(bin, "catalog", "--json")
	// Its own process group, so the deadline can take the whole tree.
	//
	// Without it the deadline DOES NOT BOUND ANYTHING: killing the generator
	// leaves any grandchild it spawned holding the output pipe, cmd.Wait never
	// returns, and the spawn hangs exactly as if there were no timeout. Found
	// by writing the test an audit asked for -- the 60s deadline was measured
	// not firing at all. Same mechanism as argano#6, one repo over.
	cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
	// No stdin, stated rather than inherited. Go's default for a nil Stdin is
	// /dev/null, so this line changes nothing today -- it exists so that a
	// later refactor setting os.Stdin has to delete an explicit decision
	// rather than fill a silence. That silence is exactly what argano#6 was
	// filed for one repo over.
	cmd.Stdin = nil
	var buf, errBuf bytes.Buffer
	cmd.Stdout = &buf
	cmd.Stderr = &errBuf
	if err := cmd.Start(); err != nil {
		return nil, err
	}
	done := make(chan error, 1)
	go func() { done <- cmd.Wait() }()
	select {
	case err := <-done:
		if err != nil {
			// argano exits non-zero when the catalog is INCOMPLETE and still
			// prints it. The partial catalog is worth keeping, but it is not
			// allowed to be reported as whole -- so the error is returned and
			// the file says so.
			return nil, fmt.Errorf("%s catalog --json failed: %w: %s", bin, err, errBuf.String())
		}
		return buf.Bytes(), nil
	case <-time.After(timeout):
		if cmd.Process != nil {
			// The GROUP, not the process. A negative pid is the group, and it
			// is safe here only because Setpgid above gave the child one of
			// its own -- without that it would name facet's own group.
			if err := syscall.Kill(-cmd.Process.Pid, syscall.SIGKILL); err != nil {
				_ = cmd.Process.Kill()
			}
		}
		<-done
		return nil, fmt.Errorf("%s catalog --json did not finish within %s", bin, timeout)
	}
}
